sudo: required
language: generic

branches:
    only:
        - master

services:
    - docker

before_install:
    - docker build -t di3go95/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true di3go95/react-test npm test

after_success:
    - docker build -t di3go95/multi-client ./client
    - docker build -t di3go95/multi-nginx ./nginx
    - docker build -t di3go95/multi-server ./server
    - docker build -t di3go95/multi-worker ./worker

    # Login to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push di3go95/multi-client
    - docker push di3go95/multi-nginx
    - docker push di3go95/multi-server
    - docker push di3go95/multi-worker
