sudo: required
language: generic

branches:
    only:
        - master

services:
    - docker

before_install:
    - docker build -t di3go95/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true di3go95/react-test npm test

after_success:
    - docker build -t di3go95/multi-client ./client
    - docker build -t di3go95/multi-nginx ./nginx
    - docker build -t di3go95/multi-server ./server
    - docker build -t di3go95/multi-worker ./worker