version: '3'
services: 
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgress_password
    redis:
        image: 'redis:latest'
    server:
        stdin_open: true    # -i
        tty: true           # -t
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules # Dont override this folder
            - /D/_projects/work/udemy/dockerAndKubernetes/git/complex/server:/app # everything in this folder is mapped to the app folder 
        environment: 
            - REDIS_HOST=redis # name of the service that we created
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres # name of the service that we created
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432